// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $api_population_composition from "./routes/api/population-composition.ts";
import * as $index from "./routes/index.tsx";
import * as $InteractiveGraph from "./islands/InteractiveGraph.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/api/population-composition.ts": $api_population_composition,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/InteractiveGraph.tsx": $InteractiveGraph,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
